india_today_parser:
  log_level: INFO
  file_name: "india_today.log"
indian_express_parser:
  log_level: INFO
  file_name: "indian_express.log"
spider:
  log_level: INFO
  file_name: "crime_news_crawler.log"
  sites_to_crawl: ["indiatoday", indianexpress]
  indiatoday.in:
    start_url: "https://www.indiatoday.in/crime"
    allow: r"https://www\.indiatoday\.in/crime(/.*)?$"
    unique: True
    follow: True
  indianexpress.com:
    start_url: "https://www.indianexpress.com/about/crime-news"
    allow: r"https://www\.indianexpress\.com/about/crime-news/"
    unique: True
    follow: True
database:
  db_name: "crime_news_db"
  username: "crimescrapper"
  host: "localhost"
  port: "5432"
  table_name: "crimedata"
  log_level: INFO
  file_name: "database.log"
pipeline:
  log_level: INFO
  file_name: "pipeline.log"
